# Generated by Django 5.1.3 on 2024-11-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelea',
            name='resultado',
            field=models.CharField(blank=True, choices=[('equipo1', 'Equipo 1 Ganó'), ('equipo2', 'Equipo 2 Ganó'), ('tie', 'Empate')], default='', help_text='Resultado del partido (Equipo 1, Equipo 2 o Empate)', max_length=10),
        ),
    ]
