# Generated by Django 5.1.3 on 2024-11-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_pelea_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
