# Generated by Django 5.1.3 on 2024-11-28 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_current'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoUserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='eventos.evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediccion', models.CharField(choices=[('equipo1', 'Equipo 1'), ('empate', 'Empate'), ('equipo2', 'Equipo 2')], max_length=10)),
                ('pelea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='eventos.pelea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
