# Generated by Django 5.1.3 on 2024-12-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_alter_evento_results_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ranking_visible',
            field=models.BooleanField(default=False),
        ),
    ]
