# Generated by Django 5.1.4 on 2025-03-23 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0008_evento_ranking_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="NombreEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("valor", models.PositiveIntegerField()),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos",
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "unique_together": {("evento", "valor")},
            },
        ),
    ]
